import Head from 'next/head'
import {Inter} from 'next/font/google'
import {css} from '@emotion/react';
import Link from "next/link";
import {APP_PATH} from "@/constants/APP_INFO";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main css={Layout}>
                <div>
                    <h1 css={Title}>in my Bucket</h1>
                    <button css={Button}>
                        <Link href={APP_PATH.MY_BUCKET}>KaKao로 계속하기</Link>
                    </button>
                </div>
            </main>
        </>
    )
}

const Layout = css`
  width: 100vw;
  height: 100vh;

  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;

  background: url("/images/pattern02.jpg") repeat;
  background-size: cover;
`;
const Title = css`
  margin-bottom: 50px;

  font-size: 3.2rem;
  font-weight: 300;
  
  color: #f7f0ed;
  text-shadow: -1px -1px 0 #76b860, 1px -1px 0 #76b860, -1px 1px 0 #76b860, 1px 1px 0 #76b860;
  
  font-family: 'Barlow Condensed', sans-serif;
  font-family: 'Noto Sans KR', sans-serif;
`;
const Button = css`
  padding: 10px 20px;

  color: #000;
  background: #ffe812;
  border-radius: 3px;

  font-size: 1.2rem;
  font-weight: 500;
`;
